//===========================================================================
//	gauntlet	version 0.1
//
//
//	Made with doktor's BotStudio v. 0.98
//	http://www.planetquake.com/botstudio  e-mail: doktor@cutey.com
//===========================================================================

#include "chars.h"

skill 1
{
	CHARACTERISTIC_NAME							"gauntlet"
	CHARACTERISTIC_GENDER						"it"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gauntlet_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/gauntlet_t.c"
	CHARACTERISTIC_CHAT_NAME					"gauntlet"
	CHARACTERISTIC_CHAT_CPM						0.0
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					1.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gauntlet_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					1.0


	CHARACTERISTIC_FIRETHROTTLE					1.0
}

skill 4
{
	CHARACTERISTIC_NAME							"gauntlet"
	CHARACTERISTIC_GENDER						"it"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gauntlet_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/gauntlet_t.c"
	CHARACTERISTIC_CHAT_NAME					"gauntlet"
	CHARACTERISTIC_CHAT_CPM						0.0
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					1.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gauntlet_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					1.0


	CHARACTERISTIC_FIRETHROTTLE					1.0
}

skill 5
{
	CHARACTERISTIC_NAME							"gauntlet"
	CHARACTERISTIC_GENDER						"it"
	CHARACTERISTIC_ATTACK_SKILL					1.0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gauntlet_w.c"
	CHARACTERISTIC_AIM_SKILL					1.0
	CHARACTERISTIC_AIM_ACCURACY					1.0
	CHARACTERISTIC_VIEW_FACTOR					1.0
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.0

	CHARACTERISTIC_CHAT_FILE					"bots/gauntlet_t.c"
	CHARACTERISTIC_CHAT_NAME					"gauntlet"
	CHARACTERISTIC_CHAT_CPM						0.0
	CHARACTERISTIC_CHAT_INSULT					0.0
	CHARACTERISTIC_CHAT_MISC					0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.0
	CHARACTERISTIC_CHAT_KILL					0.0
	CHARACTERISTIC_CHAT_DEATH					0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.0
	CHARACTERISTIC_CHAT_HITTALKING				0.0
	CHARACTERISTIC_CHAT_HITNODEATH				0.0
	CHARACTERISTIC_CHAT_HITNOKILL				0.0
	CHARACTERISTIC_CHAT_RANDOM					0.0
	CHARACTERISTIC_CHAT_REPLY					0.0

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.0
	CHARACTERISTIC_GRAPPLE_USER					1.0

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gauntlet_i.c"
	CHARACTERISTIC_AGGRESSION					1.0
	CHARACTERISTIC_SELFPRESERVATION				0.0
	CHARACTERISTIC_VENGEFULNESS					1.0
	CHARACTERISTIC_CAMPER						0.0

	CHARACTERISTIC_EASY_FRAGGER					1.0
	CHARACTERISTIC_ALERTNESS					1.0


	CHARACTERISTIC_FIRETHROTTLE					1.0
}
